#!/bin/bash

WORK_PATH=/usr/local/bin/rocs-svr
mkdir -p $WORK_PATH

echo '# 1. setup rocs-svr'
autostart_app=rocs-svr
service_file=/etc/systemd/system/$autostart_app.service
autostart_file=$WORK_PATH/start_rocs_svr.sh

is_service=$(systemctl list-units --type=service | grep $autostart_app.service)

if [ ! -z "$is_service" ]; then
  systemctl stop $autostart_app.service
fi

cp -r config/ $WORK_PATH/
cp -r script/ $WORK_PATH/
cp -r rocs_svr $WORK_PATH/
cp -r HandControl $WORK_PATH/
cp -r start_rocs_svr.sh $WORK_PATH/

user1=$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1; exit}' /etc/passwd)
sed -i "s/_user_/$user1/g" $WORK_PATH/config/application.conf

source $WORK_PATH/config/application.conf 2>/dev/null

SYSTEMD_UNIT="[Unit]
Description=Start $autostart_app at boot

[Service]
ExecStart=$autostart_file
WorkingDirectory=$WORK_PATH
Restart=on-failure
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target
"

# 创建 Systemd 单元文件
echo -e "$SYSTEMD_UNIT" | tee $service_file > /dev/null

chmod 755 $autostart_file
systemctl daemon-reload
systemctl enable $autostart_app.service
systemctl restart $autostart_app.service

echo "# ====================================== README ======================================"
echo "Setup service_file success! you can manage the service using 'systemctl <command> $autostart_app'."
echo "Please ensure that your algorithm program is located at: $sdk_ctrl_path"
echo "If you need to customize the location, you can edit: $WORK_PATH/config/application.conf"
